"""empty message

Revision ID: 49b08ed97ecf
Revises: af68ce68e062
Create Date: 2021-11-12 21:18:00.928164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b08ed97ecf'
down_revision = 'af68ce68e062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
