"""empty message

Revision ID: e85b653948ac
Revises: 512f6ce29251
Create Date: 2021-10-09 20:26:21.970692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85b653948ac'
down_revision = '512f6ce29251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isActive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isActive')
    # ### end Alembic commands ###
